// Code generated by MockGen. DO NOT EDIT.
// Source: page_parse_service.go

// Package parser is a generated GoMock package.
package parser

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/s14t284/apple-maitained-bot/domain"
)

// MockPageParseService is a mock of PageParseService interface.
type MockPageParseService struct {
	ctrl     *gomock.Controller
	recorder *MockPageParseServiceMockRecorder
}

// MockPageParseServiceMockRecorder is the mock recorder for MockPageParseService.
type MockPageParseServiceMockRecorder struct {
	mock *MockPageParseService
}

// NewMockPageParseService creates a new mock instance.
func NewMockPageParseService(ctrl *gomock.Controller) *MockPageParseService {
	mock := &MockPageParseService{ctrl: ctrl}
	mock.recorder = &MockPageParseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPageParseService) EXPECT() *MockPageParseServiceMockRecorder {
	return m.recorder
}

// ParsePage mocks base method.
func (m *MockPageParseService) ParsePage(target string, page domain.Page) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParsePage", target, page)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParsePage indicates an expected call of ParsePage.
func (mr *MockPageParseServiceMockRecorder) ParsePage(target, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParsePage", reflect.TypeOf((*MockPageParseService)(nil).ParsePage), target, page)
}
