// Code generated by MockGen. DO NOT EDIT.
// Source: ipad_service.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	model "github.com/s14t284/apple-maitained-bot/domain/model"
)

// MockIPadService is a mock of IPadService interface.
type MockIPadService struct {
	ctrl     *gomock.Controller
	recorder *MockIPadServiceMockRecorder
}

// MockIPadServiceMockRecorder is the mock recorder for MockIPadService.
type MockIPadServiceMockRecorder struct {
	mock *MockIPadService
}

// NewMockIPadService creates a new mock instance.
func NewMockIPadService(ctrl *gomock.Controller) *MockIPadService {
	mock := &MockIPadService{ctrl: ctrl}
	mock.recorder = &MockIPadServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPadService) EXPECT() *MockIPadServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockIPadService) Add(ipad *model.IPad) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ipad)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockIPadServiceMockRecorder) Add(ipad interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockIPadService)(nil).Add), ipad)
}

// Find mocks base method.
func (m *MockIPadService) Find(param *model.IPadRequestParam) (model.IPads, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", param)
	ret0, _ := ret[0].(model.IPads)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIPadServiceMockRecorder) Find(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIPadService)(nil).Find), param)
}

// FindAll mocks base method.
func (m *MockIPadService) FindAll() (model.IPads, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].(model.IPads)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIPadServiceMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIPadService)(nil).FindAll))
}

// FindByURL mocks base method.
func (m *MockIPadService) FindByURL(url string) (*model.IPad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByURL", url)
	ret0, _ := ret[0].(*model.IPad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByURL indicates an expected call of FindByURL.
func (mr *MockIPadServiceMockRecorder) FindByURL(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByURL", reflect.TypeOf((*MockIPadService)(nil).FindByURL), url)
}

// IsExist mocks base method.
func (m *MockIPadService) IsExist(ipad *model.IPad) (bool, uint, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExist", ipad)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(time.Time)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// IsExist indicates an expected call of IsExist.
func (mr *MockIPadServiceMockRecorder) IsExist(ipad interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExist", reflect.TypeOf((*MockIPadService)(nil).IsExist), ipad)
}

// Remove mocks base method.
func (m *MockIPadService) Remove(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockIPadServiceMockRecorder) Remove(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockIPadService)(nil).Remove), id)
}

// Update mocks base method.
func (m *MockIPadService) Update(ipad *model.IPad) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ipad)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIPadServiceMockRecorder) Update(ipad interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIPadService)(nil).Update), ipad)
}

// UpdateAllSoldTemporary mocks base method.
func (m *MockIPadService) UpdateAllSoldTemporary() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAllSoldTemporary")
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAllSoldTemporary indicates an expected call of UpdateAllSoldTemporary.
func (mr *MockIPadServiceMockRecorder) UpdateAllSoldTemporary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAllSoldTemporary", reflect.TypeOf((*MockIPadService)(nil).UpdateAllSoldTemporary))
}
