// Code generated by MockGen. DO NOT EDIT.
// Source: mac_service.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	model "github.com/s14t284/apple-maitained-bot/domain/model"
)

// MockMacService is a mock of MacService interface.
type MockMacService struct {
	ctrl     *gomock.Controller
	recorder *MockMacServiceMockRecorder
}

// MockMacServiceMockRecorder is the mock recorder for MockMacService.
type MockMacServiceMockRecorder struct {
	mock *MockMacService
}

// NewMockMacService creates a new mock instance.
func NewMockMacService(ctrl *gomock.Controller) *MockMacService {
	mock := &MockMacService{ctrl: ctrl}
	mock.recorder = &MockMacServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMacService) EXPECT() *MockMacServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockMacService) Add(mac *model.Mac) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", mac)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockMacServiceMockRecorder) Add(mac interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockMacService)(nil).Add), mac)
}

// Find mocks base method.
func (m *MockMacService) Find(param *model.MacRequestParam) (model.Macs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", param)
	ret0, _ := ret[0].(model.Macs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMacServiceMockRecorder) Find(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMacService)(nil).Find), param)
}

// FindAll mocks base method.
func (m *MockMacService) FindAll() (model.Macs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].(model.Macs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockMacServiceMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockMacService)(nil).FindAll))
}

// FindByURL mocks base method.
func (m *MockMacService) FindByURL(url string) (*model.Mac, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByURL", url)
	ret0, _ := ret[0].(*model.Mac)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByURL indicates an expected call of FindByURL.
func (mr *MockMacServiceMockRecorder) FindByURL(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByURL", reflect.TypeOf((*MockMacService)(nil).FindByURL), url)
}

// IsExist mocks base method.
func (m *MockMacService) IsExist(mac *model.Mac) (bool, uint, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExist", mac)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(time.Time)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// IsExist indicates an expected call of IsExist.
func (mr *MockMacServiceMockRecorder) IsExist(mac interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExist", reflect.TypeOf((*MockMacService)(nil).IsExist), mac)
}

// Remove mocks base method.
func (m *MockMacService) Remove(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockMacServiceMockRecorder) Remove(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockMacService)(nil).Remove), id)
}

// Update mocks base method.
func (m *MockMacService) Update(mac *model.Mac) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", mac)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMacServiceMockRecorder) Update(mac interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMacService)(nil).Update), mac)
}

// UpdateAllSoldTemporary mocks base method.
func (m *MockMacService) UpdateAllSoldTemporary() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAllSoldTemporary")
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAllSoldTemporary indicates an expected call of UpdateAllSoldTemporary.
func (mr *MockMacServiceMockRecorder) UpdateAllSoldTemporary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAllSoldTemporary", reflect.TypeOf((*MockMacService)(nil).UpdateAllSoldTemporary))
}
