// Code generated by MockGen. DO NOT EDIT.
// Source: scrape_service.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	goquery "github.com/PuerkitoBio/goquery"
	gomock "github.com/golang/mock/gomock"
	domain "github.com/s14t284/apple-maitained-bot/domain"
)

// MockScrapeService is a mock of ScrapeService interface.
type MockScrapeService struct {
	ctrl     *gomock.Controller
	recorder *MockScrapeServiceMockRecorder
}

// MockScrapeServiceMockRecorder is the mock recorder for MockScrapeService.
type MockScrapeServiceMockRecorder struct {
	mock *MockScrapeService
}

// NewMockScrapeService creates a new mock instance.
func NewMockScrapeService(ctrl *gomock.Controller) *MockScrapeService {
	mock := &MockScrapeService{ctrl: ctrl}
	mock.recorder = &MockScrapeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrapeService) EXPECT() *MockScrapeServiceMockRecorder {
	return m.recorder
}

// Scrape mocks base method.
func (m *MockScrapeService) Scrape(targetPath string) (*goquery.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scrape", targetPath)
	ret0, _ := ret[0].(*goquery.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scrape indicates an expected call of Scrape.
func (mr *MockScrapeServiceMockRecorder) Scrape(targetPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scrape", reflect.TypeOf((*MockScrapeService)(nil).Scrape), targetPath)
}

// ScrapeMaintainedPage mocks base method.
func (m *MockScrapeService) ScrapeMaintainedPage(doc *goquery.Document) ([]domain.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScrapeMaintainedPage", doc)
	ret0, _ := ret[0].([]domain.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScrapeMaintainedPage indicates an expected call of ScrapeMaintainedPage.
func (mr *MockScrapeServiceMockRecorder) ScrapeMaintainedPage(doc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScrapeMaintainedPage", reflect.TypeOf((*MockScrapeService)(nil).ScrapeMaintainedPage), doc)
}
